### ISSUE TITLE
Crash from GuiFileSelection when loading an empty book with title and author

### ISSUE THREAD

**Issue by waffle-stomper** [waffle-stomper/Ghostwriter#4]
This might already be fixed in 1.8.0-1.7.4

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at wafflestomper.ghostwriter.GuiFileSelection.loadPreview(GuiFileSelection.java:105)
    at wafflestomper.ghostwriter.GuiFileSelection.access$600(GuiFileSelection.java:20)
    at     wafflestomper.ghostwriter.GuiFileSelection$ScrollList.func_148144_a(GuiFileSelection.java:243)
    at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:287)
    at wafflestomper.ghostwriter.GuiFileSelection.func_146274_d(GuiFileSelection.java:168)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:516)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1662)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
```

**Comment by waffle-stomper** [comment]
Can't reproduce in 1.11.2-1.9.0.
